#!/usr/bin/env bash
# SYNAPSE VPS first-time setup (ADR-0013).
#
# Run ON the VPS as the `deploy` user, after the repo has been unpacked to
# /home/deploy/synapse/app:
#
#   bash /home/deploy/synapse/app/infra/vps/setup.sh http://<public-ip>:8081
#
# Idempotent: re-running skips everything that already exists. Secrets are
# generated on this machine and never leave it.
#
# Deliberately additive to the shared host: dedicated Node toolchain under
# /home/deploy/synapse/runtime (system Node untouched), a new role/database in
# the existing PostgreSQL cluster, Typesense bound to loopback, and a new
# nginx site on :8081. Nothing belonging to other tenants is modified.
set -euo pipefail

PUBLIC_ORIGIN="${1:?usage: setup.sh <public-origin, e.g. http://203.0.113.10:8081>}"

BASE=/home/deploy/synapse
APP="$BASE/app"
RUNTIME="$BASE/runtime/node"
ENVDIR="$BASE/env"
NODE_VERSION=22.22.3
PNPM_VERSION=11.2.1
TYPESENSE_VERSION=27.1

mkdir -p "$BASE" "$ENVDIR"
chmod 700 "$ENVDIR"

# ---- 1. Dedicated Node toolchain (system Node stays untouched) -------------
if [ ! -x "$RUNTIME/bin/node" ]; then
  echo "==> Installing Node $NODE_VERSION into $RUNTIME"
  mkdir -p "$RUNTIME"
  curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" \
    | tar -xJ -C "$RUNTIME" --strip-components=1
fi
if [ ! -x "$RUNTIME/bin/pnpm" ]; then
  echo "==> Installing pnpm $PNPM_VERSION (into the dedicated toolchain only)"
  # --prefix pins the install into the dedicated toolchain; without it the
  # host's npmrc (prefix=/usr) wins and the install EACCESes outside our dir.
  "$RUNTIME/bin/npm" install -g --prefix "$RUNTIME" "pnpm@${PNPM_VERSION}" >/dev/null
fi

# ---- 2. PostgreSQL: synapse role + database + pgvector ---------------------
echo "==> Ensuring PostgreSQL role/database"
sudo apt-get install -y -qq postgresql-16-pgvector >/dev/null

DB_PASSWORD_FILE="$ENVDIR/.db-password"
if [ ! -f "$DB_PASSWORD_FILE" ]; then
  (umask 077; openssl rand -hex 24 > "$DB_PASSWORD_FILE")
fi
DB_PASSWORD="$(cat "$DB_PASSWORD_FILE")"

if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='synapse'" | grep -q 1; then
  sudo -u postgres psql -v ON_ERROR_STOP=1 \
    -c "CREATE ROLE synapse LOGIN PASSWORD '${DB_PASSWORD}'"
fi
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='synapse_prod'" | grep -q 1; then
  sudo -u postgres createdb -O synapse synapse_prod
fi
sudo -u postgres psql -d synapse_prod -v ON_ERROR_STOP=1 \
  -c "CREATE EXTENSION IF NOT EXISTS vector"

# ---- 3. Typesense (official deb, loopback only) -----------------------------
if ! command -v typesense-server >/dev/null 2>&1; then
  echo "==> Installing Typesense $TYPESENSE_VERSION"
  curl -fsSL "https://dl.typesense.org/releases/${TYPESENSE_VERSION}/typesense-server-${TYPESENSE_VERSION}-amd64.deb" \
    -o /tmp/typesense-server.deb
  sudo apt-get install -y -qq /tmp/typesense-server.deb >/dev/null
  rm -f /tmp/typesense-server.deb
fi

TS_KEY_FILE="$ENVDIR/.typesense-key"
if [ ! -f "$TS_KEY_FILE" ]; then
  (umask 077; openssl rand -hex 24 > "$TS_KEY_FILE")
fi
TS_KEY="$(cat "$TS_KEY_FILE")"

sudo tee /etc/typesense/typesense-server.ini >/dev/null <<INI
; Managed by SYNAPSE infra/vps/setup.sh — loopback only (ADR-0013).
[server]
api-address = 127.0.0.1
api-port = 8108
data-dir = /var/lib/typesense
api-key = ${TS_KEY}
log-dir = /var/log/typesense
INI
sudo systemctl enable typesense-server >/dev/null 2>&1 || true
sudo systemctl restart typesense-server

# ---- 4. Env files (secrets stay on this machine) ----------------------------
AUTH_SECRET_FILE="$ENVDIR/.auth-secret"
if [ ! -f "$AUTH_SECRET_FILE" ]; then
  (umask 077; openssl rand -hex 32 > "$AUTH_SECRET_FILE")
fi
AUTH_SECRET="$(cat "$AUTH_SECRET_FILE")"

# http://host:8081 -> ws://host:8081/sync (https -> wss automatically).
SYNC_WS_URL="ws${PUBLIC_ORIGIN#http}/sync"

(umask 077; cat > "$ENVDIR/api.env" <<ENV
# Generated by infra/vps/setup.sh — never commit. Consumed by synapse-api
# (systemd) and by deploy.sh for builds/migrations.
DATABASE_URL=postgres://synapse:${DB_PASSWORD}@127.0.0.1:5432/synapse_prod
BETTER_AUTH_URL=${PUBLIC_ORIGIN}
BETTER_AUTH_SECRET=${AUTH_SECRET}
WEB_ORIGIN=${PUBLIC_ORIGIN}
TYPESENSE_URL=http://127.0.0.1:8108
TYPESENSE_API_KEY=${TS_KEY}
API_PORT=8790
API_HOST=127.0.0.1
# Build-time inputs for apps/web (read via deploy.sh).
VITE_API_URL=${PUBLIC_ORIGIN}
VITE_SYNC_URL=${SYNC_WS_URL}
ENV
)

SYNC_INTERNAL_SECRET_FILE="$ENVDIR/.sync-internal-secret"
if [ ! -f "$SYNC_INTERNAL_SECRET_FILE" ]; then
  (umask 077; openssl rand -hex 24 > "$SYNC_INTERNAL_SECRET_FILE")
fi
SYNC_INTERNAL_SECRET="$(cat "$SYNC_INTERNAL_SECRET_FILE")"

(umask 077; cat > "$ENVDIR/sync.env" <<ENV
# Generated by infra/vps/setup.sh — never commit. Consumed by synapse-sync.
DATABASE_URL=postgres://synapse:${DB_PASSWORD}@127.0.0.1:5432/synapse_prod
SYNC_PORT=8791
SYNC_HOST=127.0.0.1
# Internal doc-write API (ADR-0011) — loopback only. Consumed by the MCP
# server on this host (infra/vps/mcp-stdio.sh); never expose beyond 127.0.0.1.
SYNC_INTERNAL_PORT=1235
SYNC_INTERNAL_HOST=127.0.0.1
SYNC_INTERNAL_SECRET=${SYNC_INTERNAL_SECRET}
ENV
)

# ---- 5. Web root -------------------------------------------------------------
sudo mkdir -p /var/www/synapse
sudo chown deploy:deploy /var/www/synapse

# ---- 6. systemd units + nginx site -------------------------------------------
echo "==> Installing systemd units and nginx site"
sudo cp "$APP/infra/vps/synapse-api.service" /etc/systemd/system/synapse-api.service
sudo cp "$APP/infra/vps/synapse-sync.service" /etc/systemd/system/synapse-sync.service
sudo systemctl daemon-reload
sudo systemctl enable synapse-api synapse-sync >/dev/null 2>&1 || true

sudo cp "$APP/infra/vps/nginx-synapse.conf" /etc/nginx/sites-available/synapse
sudo ln -sf /etc/nginx/sites-available/synapse /etc/nginx/sites-enabled/synapse
sudo nginx -t
sudo systemctl reload nginx

echo "==> Setup complete. Next: bash $APP/infra/vps/deploy.sh"
